version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123asd
      POSTGRES_DB: chatbot
    ports:
      - "5439:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db